#!/bin/sh

# $Id$

[ -e /var/run/automount.pid ] && kill -TERM $( cat /var/run/automount.pid )
[ -e /tmp/tuxmaild.pid ] && kill $( cat /tmp/tuxmaild.pid )
[ -e /tmp/tuxcald.pid ] && kill $( cat /tmp/tuxcald.pid )

switch -fnc 0 -fblk 0
